import type { Metadata } from "next";
import { Oxanium } from "next/font/google";
import "./globals.css";
import { HeaderApp } from "@/components/header/HeaderApp";
import Footer from "@/components/Footer/Footer";

const geistSans = Oxanium({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-oxanium' 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <HeaderApp />
       <main className="lg:pt-24">
       {children}
       </main>
        <Footer></Footer>
      </body>

    </html>
  );
}
